baseURL = "https://splintersfury.github.io/mal_blog/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Reverse Engineering Attempts"

# Change the default theme to be use when building the site with Hugo
theme = "DoIt"

[params]
  # DoIt theme version
  version = "0.2.X"

[menu]
  [[menu.main]]
    identifier = "post"
    # ... (your existing posts entry)
    name = "Post"
    url = "/post/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    # ... (your existing tags entry)
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    # ... (your existing categories entry)
    name = "Categories"
    url = "/categories/"
    weight = 3
  [[menu.main]] # New entry for About page
    identifier = "about"
    pre = ""
    post = ""
    name = "About Me"
    url = "/about/" # This should match the filename (e.g., content/about.md)
    title = "Learn more about me"
    weight = 4    # Adjust weight to control order

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[caches]
  [caches.images]
    dir = ":cacheDir/images"